name: Generate Snake

on:
  schedule: # Executa o script a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository content
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Run the Snake action to generate the SVG
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: xOryus  # Seu nome de usuário
          svg_out_path: dist/snake.svg

      # Deploy the generated Snake animation to the branch output
      - name: Push generated Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
