name: Generate Snake

on:
  schedule: # Executa o script a cada 6 horas para manter a snake atualizada
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permite que o workflow seja disparado manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa a ação para gerar a snake
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      # Gera o gráfico de snake baseado na sua grade de contribuições
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: xOryus # Substitua por seu nome de usuário
          outputs: dist/snake.svg

      # Faz upload do arquivo snake.svg gerado para o repositório na branch "output"
      - name: Push Snake Animation to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
